version: "3.9"

networks:
  app-network:
    driver: bridge

services:
  ####### MONGODB ################
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=test_fastapi"
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=admin"
    command:
      mongod --quiet --logpath /dev/null
    networks:
      - app-network
  ####### APP #########################
  fastapi-app:
    build: .
    container_name: app_container
    command: bash -c "/opt/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network